services:
  appointment.database:
    image: postgres
    container_name: appointment.datahase
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: appointmentdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appointment.network

  appointment.api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appointment.api
    depends_on:
      - appointment.database
    ports:
      - "5056:80"
    networks:
      - appointment.network

volumes:
  postgres_data:

networks:
  appointment.network:
    driver: bridge